baseURL = "http://example.org/"
languageCode = "es"
title = "Home"

theme = "hugo-coder"

defaultcontentlanguage = "es"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Omar Aparicio"
    description = "Compilando..."
    keywords = "blog,development,Software,personal"
    info = "Software Developer and Arcade Gamer"
    avatarurl = "images/avatar.jpg"
    footercontent = "Compilando ..."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "auto" (use preference set by browser)
     # "dark" (dark background, light foreground)
     # "light" (light background, dark foreground) (default)
     colorscheme = "light"
 
     # Series see also post count
     maxSeeAlsoItems = 5
 
     # Custom CSS
     custom_css = []
 
     # Custom JS
     custom_js = []
 
 [taxonomies]
   category = "categories"
   series = "series"
   tag = "tags"
 
 [[params.social]]
     name = "Github"
     icon = "fab fa-github"
     weight = 1
     url = "https://github.com/omaraparicio07/"
 [[params.social]]
     name = "Gitlab"
     icon = "fab fa-gitlab"
     weight = 2
     url = "https://gitlab.com/omaraparicio07/"
 [[params.social]]
     name = "Twitter"
     icon = "fab fa-twitter"
     weight = 3
     url = "https://twitter.com/omaraparicio07/"
 [[params.social]]
     name = "LinkedIn"
     icon = "fab fa-linkedin"
     weight = 4
     url = ""

[languages]
     [languages.es]
         languagename = "Español"
 
         [languages.es.menu]
 
             [[languages.es.menu.main]]
             name = "Sobre mi"
             weight = 1
             url = "about/"
 
             [[languages.es.menu.main]]
             name = "Blog"
             weight = 2
             url = "posts/"
 
             [[languages.es.menu.main]]
             name = "Referencias"
             weight = 3
             url = "projects/"
 
             [[languages.es.menu.main]]
             name = "Contact me"
             weight = 5
             url = "contact/"

     [languages.en]
         languagename = "English"
 
         [languages.en.menu]
 
             [[languages.en.menu.main]]
             name = "About"
             weight = 1
             url = "about/"
 
             [[languages.en.menu.main]]
             name = "Blog"
             weight = 2
             url = "posts/"
 
             [[languages.en.menu.main]]
             name = "Projects"
             weight = 3
             url = "projects/"
 
             [[languages.en.menu.main]]
             name = "Contact me"
             weight = 5
             url = "contact/"

